language: python
python:
  - "2.7"
install:
  # installing the `barrel` package - the dependencies will be installed
  - python setup.py install
script:
  # all the tests
  - python -m unittest discover barrel.tests
notifications:
  # send the notification about the build results
  email:
    recipients:
      - web-dev@txtr.com
    on_success: change
    on_failure: change
